name: Sync Upstream Theme

on:
    workflow_run:
      workflows: ["Delete workflows"]
      types:
        - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set timezone to China
        run: |
          sudo timedatectl set-timezone Asia/Shanghai

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: luci-theme-bootstrap

      - name: Sync upstream theme
        run: |
          cd luci-theme-bootstrap
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' ! -name 'README.md' -exec rm -rf {} +
          git clone -b master --single-branch --filter=blob:none https://github.com/openwrt/luci.git upstream
          LATEST_COMMIT=$(cd upstream && git log -1 --pretty=format:"%s" themes/luci-theme-bootstrap)
          LATEST_DATE=$(cd upstream && git log -1 --pretty=format:"%cI" themes/luci-theme-bootstrap)
          LATEST_AUTHOR=$(cd upstream && git log -1 --pretty="%an <%ae>" themes/luci-theme-bootstrap)
          echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_ENV
          echo "latest_date=$LATEST_DATE" >> $GITHUB_ENV
          echo "latest_author=$LATEST_AUTHOR" >> $GITHUB_ENV
          cp -r upstream/themes/luci-theme-bootstrap/* .
          rm -rf upstream
      
      - name: Commit and push changes
        run: |
          ls -la
          cd luci-theme-bootstrap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{ env.latest_commit }}" --author="${{ env.latest_author }}" --date="${{ env.latest_date }}"
          git push
